name: Run the unit test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/Checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.14'

    - name: Intsall Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest
      